server:
  port: 8081
---

spring:
  config:
    activate:
      on-profile: local
  test:
    profile-name : local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/basic_backend?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: basic
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          privider_disables_autocommit: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
cloud:
  aws:
    s3:
      bucket: basicbackendbucket
    credentials:
      access-key: AKIA6Q5VVRET5H5ONKVG
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
oauth2:
  google:
    client-id: 576976531948-o101aso5o6q4gbdphjgpsmjifn3kb2mg.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8081/auth/google
    authorization-server-uri: https://oauth2.googleapis.com/token
    resource-server-uri: https://www.googleapis.com/oauth2/v2/userinfo

---

spring:
  config:
    activate:
      on-profile: dev
  test:
    profile-name : dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/basic_backend?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: basic
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          privider_disables_autocommit: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher