server:
  port: 8080
---

spring:
  config:
    activate:
      on-profile: local
  test:
    profile-name : local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/basic_backend?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: basic
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          privider_disables_autocommit: true

---

spring:
  config:
    activate:
      on-profile: dev
  test:
    profile-name : dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/basic_backend?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: basic
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          privider_disables_autocommit: true