server:
  port: 8081
---

spring:
  config:
    activate:
      on-profile: local
  test:
    profile-name : local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/basic_backend?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: basic
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          privider_disables_autocommit: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
cloud:
  aws:
    s3:
      bucket: basicbackendbucket
    credentials:
      access-key: AKIA6Q5VVRX6VJ5ONKVG
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

---

spring:
  config:
    activate:
      on-profile: dev
  test:
    profile-name : dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/basic_backend?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: basic
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          privider_disables_autocommit: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher